schema = 3

[project]
name = "crypto370"
version = "1.0.2-dev"
kind = "library"

[toolchain]
cc370 = "1.4.0"
libc370 = "2.4.1"
mbt = "3.0"

[build]

[lib]
name = "crypto370"
sources = ["src/*.c"]
headers = ["include/sha256.h", "include/blowfish.h", "include/base64.h"]

[tests]
rent = false
reus = false

[test.TSTSHA]
sources = [
  "test/mvs/tstsha.c",
  "src/sha256i.c",
  "src/sha256u.c",
  "src/sha256f.c",
  "src/sha256t.c",
]

[test.TSTBFISH]
sources = [
  "test/mvs/tstbfish.c",
  "src/bfishkey.c",
  "src/bfishenc.c",
  "src/bfishdec.c",
]

[test.TSTB64]
sources = ["test/mvs/tstb64.c", "src/b64enc.c", "src/b64dec.c", "src/b64tbl.c"]
